name: CI - Testing

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run TypeScript build
      run: npm run build
    
    - name: Check dist folder exists
      run: |
        if [ ! -d "dist" ]; then
          echo "Error: dist folder not found after build!"
          exit 1
        fi
        echo "dist folder created successfully"
        ls -la dist/
    
    - name: Run Auth tests
      run: npm run test:auth
      continue-on-error: false
    
    - name: Run Queue tests
      run: npm run test:queue
      continue-on-error: false
    
    - name: Run all tests
      run: npm test
      continue-on-error: false
    
    - name: Test Summary
      if: always()
      run: |
        echo "✅ Testing completed"
        echo "Branch: ${{ github.ref }}"
        echo "Commit: ${{ github.sha }}"

